###获取状态
GET {{host}}/api/status
Content-Type: application/x-www-form-urlencoded

###登录
POST {{host}}/api/user/login
Content-Type: application/json

{"username": "root","password":"123456"}

###查看账户信息
GET {{host}}/api/user/self
Content-Type: application/x-www-form-urlencoded

###修改账户信息
PUT {{host}}/api/user/self
Content-Type: application/json

{"display_name": "root"}

###删除用户
DELETE {{host}}/api/user/self/

###获取登录accesstoken
GET {{host}}/api/user/token
Content-Type: application/x-www-form-urlencoded

###获取所有chat访问token
GET {{host}}/api/token
Content-Type: application/x-www-form-urlencoded

###新建token
POST {{host}}/api/token/
Content-Type: application/json
Authorization: 66459398d897400cb7539937f4ecd2ff

{"name": "test4","expired_time": -1,"unlimited_quota": true}

###openai 聊天接口
POST {{host}}/v1/chat/completions
Content-Type: application/json; charset=UTF-8
Authorization: {{Authorization-openai}}

{"stream": true,"model": "gpt-3.5-turbo","messages": [{"role": "user", "content": "who are you."}]}

###讯飞 聊天接口
POST {{host}}/v1/chat/completions
Content-Type: application/json
Authorization: {{Authorization-xunfei}}
Accept-Charset: utf-8

{
    "stream": true,"model": "SparkDesk","messages": [{"role": "user", "content": "Just tell me your name. No other information."}]
}

###智普 聊天接口
POST {{host}}/v1/chat/completions
Content-Type: application/json
Authorization: {{Authorization-zhipu}}
Accept-Charset: utf-8

{
  "stream": true,"model": "chatglm_std","messages": [{"role": "user", "content": "Just tell me your name. No other information."}]
}