###获取openai的所有模型
GET {{host}}/v1/models
Content-Type: application/x-www-form-urlencoded
Authorization: NbNs5ThVaPMoanMr1a5fA601A0B74eF9B8C41862D4C73b21

###获取openai某一个模型  比如：dall-e
GET {{host}}/v1/models/dall-e
Content-Type: application/x-www-form-urlencoded
Authorization: NbNs5ThVaPMoanMr1a5fA601A0B74eF9B8C41862D4C73b21

###生成图片
POST {{host}}/v1/images/generations
Content-Type: application/json
Authorization: {{Authorization-openai}}

{"prompt": "一只小猫","n": 1,"size": "256x256"}

###修改图片
POST {{host}}/v1/images/edits
Content-Type: application/json
Authorization: NbNs5ThVaPMoanMr1a5fA601A0B74eF9B8C41862D4C73b21

{"mask": "","image": "test","prompt": "Make the animation in the picture green","n": 1,"size": "1024x1024","response_format": "url"}