###获取openai的所有模型
GET {{host}}/v1/models
Content-Type: application/x-www-form-urlencoded
Authorization: NbNs5ThVaPMoanMr1a5fA601A0B74eF9B8C41862D4C73b21

###获取openai某一个模型  比如：dall-e
GET {{host}}/v1/models/dall-e
Content-Type: application/x-www-form-urlencoded
Authorization: NbNs5ThVaPMoanMr1a5fA601A0B74eF9B8C41862D4C73b21

###生成图片
POST {{host}}/v1/images/generations
Content-Type: application/json
Authorization: boFCjheSF0Bv71lr257320877f4c4eCd9a3e599515930056

{"prompt": "山川河流，CG，充满色彩的，高质量，高清，4K杰作，CG渲染，电影镜头，完美光影，风景，阳光，完美的天空，漂亮的天空，蓝天白云，完美的树木","n": 1,"size": "1024x1024"}

###修改图片
POST {{host}}/v1/images/edits
Content-Type: application/json
Authorization: NbNs5ThVaPMoanMr1a5fA601A0B74eF9B8C41862D4C73b21

{"mask": "","image": "test","prompt": "Make the animation in the picture green","n": 1,"size": "1024x1024","response_format": "url"}